# Generated by Django 3.2.4 on 2021-06-06 21:15

from django.db import migrations, models
import django.db.models.deletion
import pokedex.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('base_experience', models.IntegerField(default=0, verbose_name='Base Experience')),
                ('hp', models.IntegerField(default=0, verbose_name='HP')),
                ('attack', models.IntegerField(default=0, verbose_name='Attack')),
                ('defense', models.IntegerField(default=0, verbose_name='Defense')),
                ('special_attack', models.IntegerField(default=0, verbose_name='Special Attack')),
                ('special_defense', models.IntegerField(default=0, verbose_name='Special Defense')),
                ('speed', models.IntegerField(default=0, verbose_name='Speed')),
                ('image', models.ImageField(blank=True, null=True, upload_to=pokedex.models.pokemon_upload_dir, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemons',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('effect', models.CharField(max_length=255, verbose_name='Effect')),
                ('short_effect', models.CharField(max_length=255, verbose_name='Short Effect')),
            ],
            options={
                'verbose_name': 'Ability',
                'verbose_name_plural': 'Abilities',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Pokemon Type',
                'verbose_name_plural': 'Pokemon Types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PokemonTypeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(verbose_name='Slot')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon', verbose_name='Pokemon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemontype', verbose_name='Pokemon Type')),
            ],
            options={
                'verbose_name': 'Pokemon Type with Slot',
                'verbose_name_plural': 'Pokemon Types with Slot',
                'ordering': ['pokemon', 'slot'],
            },
        ),
        migrations.CreateModel(
            name='PokemonAbilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(verbose_name='Slot')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemonability', verbose_name='Ability')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon', verbose_name='Pokemon')),
            ],
            options={
                'verbose_name': 'Pokemon Ability with Slot',
                'verbose_name_plural': 'Pokemon Abilities with Slot',
                'ordering': ['id'],
            },
        ),
    ]
